# Header
menu:
  Home: /
  Archives: /archives
github: https://github.com/harneksidhu
linkedin: https://ca.linkedin.com/in/harneksidhu

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png